#!/usr/bin/env bash
# BamOS Hardware Detection
# Usage: sudo bamos-detect-hardware
# Detects NVIDIA/AMD/Intel GPUs and generates /etc/bamos/gpu-config.nix
set -euo pipefail

# ── Check root ──
if [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run as root (use sudo)."
  echo "Example: sudo bamos-detect-hardware"
  exit 1
fi

BAMOS_DIR="/etc/bamos"
mkdir -p "$BAMOS_DIR"

echo "============================================"
echo "   BamOS Hardware Detection"
echo "============================================"

# 1. nixos-generate-config (skip on live ISO)
if command -v nixos-generate-config &>/dev/null; then
  echo "- Generating hardware-configuration.nix..."
  if nixos-generate-config --root / --dir "$BAMOS_DIR" 2>/dev/null; then
    echo "  OK: $BAMOS_DIR/hardware-configuration.nix"
  else
    echo "  Skip: live ISO mode (no target root)"
  fi
else
  echo "- Skip: nixos-generate-config not available"
fi

# 2. GPU Detection
echo "- Detecting GPUs..."
GPU_CONFIG="$BAMOS_DIR/gpu-config.nix"

# ════════════════════════════════════════════════════════
# Write the Nix header. NOTE: we CANNOT use a quoted heredoc
# ('EOF') here because we need $ variables to expand below.
# The header lines use the same delimiter (cat >> ... << EOF).
# ════════════════════════════════════════════════════════
cat > "$GPU_CONFIG" << EOF
# Auto-generated by bamos-detect-hardware
# Run: sudo bamos-detect-hardware
{ config, lib, ... }: let
  cfg = config.bamos.hardware;
in lib.mkIf cfg.detect {
EOF

HAS_NVIDIA=false
HAS_AMD=false
NVIDIA_PCI=""
INTEL_PCI=""
AMD_PCI=""

# Parse lspci — runs in current shell (not subshell) via <<< redirection
while IFS=' ' read -r pci_addr rest; do
  [ -z "$pci_addr" ] && continue

  # Extract bus, device, function from "00:02.0"
  bus_hex="${pci_addr%%:*}"
  dev_func="${pci_addr#*:}"
  dev_hex="${dev_func%.*}"
  func_hex="${dev_func##*.}"

  # Convert hex to decimal
  bus=$(( 16#${bus_hex} ))
  dev=$(( 16#${dev_hex} ))
  func=$(( 16#${func_hex} ))
  NIX_PCI="PCI:${bus}:${dev}:${func}"

  # Detect vendor from description (lowercase)
  desc_lower="$(echo "$rest" | tr '[:upper:]' '[:lower:]')"

  case "$desc_lower" in
    *nvidia*)
      HAS_NVIDIA=true; NVIDIA_PCI="$NIX_PCI"
      echo "    # NVIDIA: $rest" >> "$GPU_CONFIG"
      echo "    #    PCI: $pci_addr -> $NIX_PCI" >> "$GPU_CONFIG"
      echo "  -> NVIDIA: $rest"
      ;;
    *intel*)
      INTEL_PCI="$NIX_PCI"
      echo "    # Intel: $rest" >> "$GPU_CONFIG"
      echo "    #    PCI: $pci_addr -> $NIX_PCI" >> "$GPU_CONFIG"
      echo "  -> Intel: $rest"
      ;;
    *amd*|*ati*)
      HAS_AMD=true; AMD_PCI="$NIX_PCI"
      echo "    # AMD: $rest" >> "$GPU_CONFIG"
      echo "    #    PCI: $pci_addr -> $NIX_PCI" >> "$GPU_CONFIG"
      echo "  -> AMD: $rest"
      ;;
  esac
done <<< "$(lspci 2>/dev/null | grep -E '(VGA compatible|3D controller|Display controller)' || true)"

# 3. NVIDIA config block (UNQUOTED EOF — $variables MUST expand)
if [ "$HAS_NVIDIA" = true ]; then
  echo "  -> Configuring NVIDIA driver + PRIME bus IDs"
  cat >> "$GPU_CONFIG" << EOF

  hardware.nvidia = {
    modesetting.enable = true;
    nvidiaSettings = true;
    powerManagement = {
      enable = lib.mkDefault true;
      finegrained = lib.mkDefault true;
    };
  };

  hardware.nvidia.prime = {
    intelBusId = "${INTEL_PCI}";
    nvidiaBusId = "${NVIDIA_PCI}";
  };

  boot.blacklistedKernelModules = [ "nouveau" ];
  boot.kernelModules = [ "nvidia_drm" "nvidia_modeset" "nvidia_uvm" "nvidia" ];
  boot.kernelParams = [ "nvidia_drm.fbdev=1" "nvidia_drm.modeset=1" ];
EOF
fi

# 4. AMD config block (UNQUOTED EOF — $variables MUST expand)
if [ "$HAS_AMD" = true ]; then
  echo "  -> Configuring AMDGPU driver"
  cat >> "$GPU_CONFIG" << EOF

  hardware.amdgpu = {
    enable = lib.mkDefault true;
    amdgpuBusId = "${AMD_PCI}";
  };
EOF
fi

# 5. Close Nix expression
echo "}" >> "$GPU_CONFIG"

# 6. Summary
echo ""
echo "============================================"
echo "   Detection complete!"
echo "============================================"
echo "   Config: $GPU_CONFIG"
echo ""
echo "   The config is auto-loaded by bamos.hardware.detect module."
echo "   Rebuild to apply:"
echo "     sudo nixos-rebuild switch --flake .#\$(hostname)"
echo ""
grep -E "(nvidiaBusId|intelBusId|amdgpuBusId)" "$GPU_CONFIG" 2>/dev/null || echo "   No discrete GPU detected"
