# flake.nix — BamOS User Configuration
# Generated by BamOS Calamares installer
#
# Usage:
#   sudo nix flake update                         # Update inputs
#   sudo nixos-rebuild switch --flake .#bamos     # Apply config
#   sudo bam update                                # Same via bam CLI
#
{
  description = "BamOS — My Configuration";

  inputs = {
    # Nixpkgs stable channel
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";

    # BamOS flake — cung cấp modules, editions, packages
    bamos.url = "github:quocnho/bamos";
  };

  outputs =
    { nixpkgs, bamos, ... }:
    let
      system = "x86_64-linux";
    in
    {
      nixosConfigurations."bamos" = nixpkgs.lib.nixosSystem {
        inherit system;
        modules = [
          # Base configuration (hostname, locale, user)
          ./configuration.nix

          # BamOS modules (import tất cả modules mặc định)
          bamos.nixosModules.default

          # Edition-specific config (sinh ra bởi Calamares)
          ./customized.nix

          # User customizations (không bị ghi đè)
          ./customConfig/default.nix
        ];

        specialArgs = {
          pkgs-unstable = import nixpkgs {
            inherit system;
            config.allowUnfree = true;
          };
        };
      };
    };
}
