# flake.nix — BamOS User Configuration
# Generated by BamOS Calamares installer
#
# Cấu trúc thư mục /etc/nixos/:
#   ├── flake.nix                  # File này — định nghĩa inputs + outputs
#   ├── flake.lock                 # Tự động sinh bởi 'nix flake update'
#   ├── configuration.nix          # Cấu hình chính (hostname, locale, user)
#   ├── customized.nix             # Edition + Machine Type (Calamares sinh)
#   ├── hardware-configuration.nix # Tự động sinh bởi nixos-generate-config
#   ├── modules/                   # Modules người dùng (thêm/xóa tùy ý)
#   │   └── default.nix            #   Aggregator — import các module con
#   ├── customConfig/              # Cấu hình cá nhân (không bị ghi đè khi cài lại)
#   │   └── default.nix            #   Thêm config của bạn ở đây
#   ├── home.nix                   # Home-manager config (optional)
#   └── secrets/                   # (Optional) Encrypted secrets
#
# Usage:
#   sudo nix flake update              # Update inputs (nixpkgs + bamos)
#   sudo nixos-rebuild switch --flake .#bamos     # Apply config
#   sudo bam update                              # Same via bam CLI
#
# Build custom ISO:
#   bam iso                          # Build GNOME ISO
#   bam iso kde --vm                 # Build KDE ISO + test trong VM
#   bam share iso                    # Build ISO với config hiện tại
#
{
  description = "BamOS — My Configuration";

  inputs = {
    # Nixpkgs (unstable channel — mới nhất)
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";

    # BamOS distro — cung cấp modules, editions, packages
    bamos.url = "github:quocnho/bamos";

    # (Optional) Home-manager — quản lý user-level config
    # home-manager.url = "github:nix-community/home-manager";
    # home-manager.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs =
    { nixpkgs, bamos, ... }@inputs:
    let
      system = "x86_64-linux";
      lib = nixpkgs.lib;
    in
    {
      nixosConfigurations."bamos" = lib.nixosSystem {
        inherit system;
        specialArgs = { inherit inputs; };

        modules = [
          # ════════════════════════════════════════════════
          # 1. Cấu hình cơ bản: hostname, locale, user
          # ════════════════════════════════════════════════
          ./configuration.nix

          # ════════════════════════════════════════════════
          # 2. BamOS core modules (bắt buộc)
          # Bao gồm: system, locale, audio, input-method (Fcitx5+Bamboo),
          #          NVIDIA, hardware detection, power management,
          #          backup, update engine, branding
          # ════════════════════════════════════════════════
          bamos.nixosModules.default

          # ════════════════════════════════════════════════
          # 3. Edition profile (do Calamares chọn khi cài)
          #    standard | developers | gaming | studio
          # ════════════════════════════════════════════════
          ./customized.nix

          # ════════════════════════════════════════════════
          # 4. User modules (thêm cấu hình theo nhu cầu)
          #    Mở rộng: thêm file .nix vào modules/ và import ở đây
          # ════════════════════════════════════════════════
          ./modules

          # ════════════════════════════════════════════════
          # 5. Custom config (KHÔNG bị ghi đè khi cài lại)
          #    Đây là nơi lý tưởng để thêm cấu hình cá nhân
          # ════════════════════════════════════════════════
          ./customConfig

          # ════════════════════════════════════════════════
          # 6. Hardware config (tự động sinh)
          # ════════════════════════════════════════════════
          ./hardware-configuration.nix

          # (Optional) Home-manager
          # inputs.home-manager.nixosModules.home-manager
          # {
          #   home-manager.useGlobalPkgs = true;
          #   home-manager.useUserPackages = true;
          #   home-manager.users.bamos = import ./home.nix;
          # }
        ];
      };
    };
}
