# BamOS NVIDIA — Wayland & GTK fixes
# GSK_RENDERER=gl: workaround for GTK4 apps not opening on NVIDIA
# GBM_BACKEND=nvidia-drm: Wayland with NVIDIA
GBM_BACKEND=nvidia-drm
__GLX_VENDOR_LIBRARY_NAME=nvidia
WLR_NO_HARDWARE_CURSORS=1
GSK_RENDERER=gl
