---
efi:
  mountPoint: "/boot"
  recommendedSize: "1GiB"
  minimumSize: "32MiB"
  label: "EFI"
userSwapChoices:
- none
- small
- suspend
luksGeneration: luks2
defaultFileSystemType: "btrfs"
availableFileSystemTypes:
- ext4
- btrfs
- xfs
- f2fs
showNotEncryptedBootMessage: false
partitionLayout:
- name: "BamOS (Btrfs)"
  filesystem: "btrfs"
  noEncrypt: false
  mountPoint: "/"
  size: "100%"
